# Generated by Django 3.1.7 on 2021-07-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SugText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('user_account', models.CharField(max_length=20, null=True)),
                ('sug_text', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
