# Generated by Django 3.1.7 on 2021-07-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugtext',
            name='create_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='sugtext',
            table='sug_text',
        ),
    ]
