# Generated by Django 3.1.7 on 2021-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20210719_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mark', models.CharField(max_length=1000, null=True)),
                ('username', models.CharField(max_length=15, null=True)),
                ('other_user', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
