# Generated by Django 3.1.7 on 2021-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
