# Generated by Django 3.1.7 on 2021-07-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_project_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.IntegerField(auto_created=True, null=True),
        ),
        migrations.AlterModelTable(
            name='project',
            table='test_project',
        ),
        migrations.AlterModelTable(
            name='sugtext',
            table='test_sug_text',
        ),
    ]
