# Generated by Django 3.1.7 on 2021-07-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_apis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apis',
            new_name='Api',
        ),
    ]
